# Solar Eclipses

What is the average duration of total darkness during a total solar eclipse? When did the longest solar eclipse occur?

The file `solar-eclipses.csv` provides information on all solar eclipses from 1901 to 2100, leveraging the ability of scientists to accurately predict the timing and location of future eclipses.

A solar eclipse happens when the Moon moves between the Earth and the Sun, blocking the Sun's light either partially or completely. There are three primary types of solar eclipses:

1. Total Solar Eclipse: The Moon fully covers the Sun, casting a shadow on Earth and revealing the Sun's corona.

2. Partial Solar Eclipse: The Moon obscures only part of the Sun, creating a crescent-shaped appearance.

3. Annular Solar Eclipse: The Moon covers the center of the Sun, leaving a ring-like appearance, known as a "ring of fire," around the edges. This occurs when the Moon is too far from Earth to completely cover the Sun.

The `duration` variable indicates the length of time that the entire moon covers the sun.

In [12]:
import pandas as pd
pd.set_option('display.max_colwidth', 1000)
df = pd.read_csv('solar-eclipses.csv')
df

,date,eclipse_type,magnitude,duration,region
0,05-18-1901,Total,1.068,06m29s,"s Asia, Australia, e Africa [Total: Indonesia, N Guinea, Madagascar]"
1,11-11-1901,Annular,0.922,11m01s,"ne Africa, Asia, w Europe [Annular: ne Africa, India, Sri Lanka, se Asia]"
2,04-08-1902,Partial,0.064,NaN,northern Canada
3,05-07-1902,Partial,0.859,NaN,"New Zealand, South Pacific"
4,10-31-1902,Partial,0.696,NaN,"c Asia, e Europe"
...,...,...,...,...,...
439,10-24-2098,Partial,0.006,NaN,Southern Ocean (near Antarctica)
440,03-21-2099,Annular,0.932,07m32s,"Australia, N.Z., Antarctica, N. America [Annular: Central Pacific]"
441,09-14-2099,Total,1.068,05m18s,"Americas, Africa [Total: Canada, U.S., Central Atlantic]"
442,03-10-2100,Annular,0.934,07m29s,"Australia, N. America [Annular: Central Pacific, U.S.]"
443,09-04-2100,Total,1.040,03m32s,"Africa, Antarctica [Total: Central Africa, Madagascar]"

### Project Ideas:

- When did the longest solar eclipse occur? The longest total eclipse?

- What is the average duration of total solar eclipses? 

- Show the next 10 solar eclipses?

In [13]:
tot_eclip = df.loc[df['eclipse_type'] == 'Total', ['date','eclipse_type', 'duration']]
tot_eclip

           date eclipse_type duration
0    05-18-1901        Total   06m29s
6    09-21-1903        Total   02m12s
8    09-09-1904        Total   06m20s
10   08-30-1905        Total   03m46s
14   01-14-1907        Total   02m25s
..          ...          ...      ...
431  06-02-2095        Total   03m18s
433  05-22-2096        Total   06m06s
435  05-11-2097        Total   03m10s
441  09-14-2099        Total   05m18s
443  09-04-2100        Total   03m32s

[135 rows x 3 columns]

In [14]:
tot_eclip.info()

<class 'pandas.DataFrame'>
Index: 135 entries, 0 to 443
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          135 non-null    str
 1   eclipse_type  135 non-null    str
 2   duration      135 non-null    str
dtypes: str(3)
memory usage: 4.2 KB

In [15]:
tot_eclip['duration'].isna().sum()

np.int64(0)

In [16]:
tot_eclip = tot_eclip.dropna(subset=['duration'])
tot_eclip

           date eclipse_type duration
0    05-18-1901        Total   06m29s
6    09-21-1903        Total   02m12s
8    09-09-1904        Total   06m20s
10   08-30-1905        Total   03m46s
14   01-14-1907        Total   02m25s
..          ...          ...      ...
431  06-02-2095        Total   03m18s
433  05-22-2096        Total   06m06s
435  05-11-2097        Total   03m10s
441  09-14-2099        Total   05m18s
443  09-04-2100        Total   03m32s

[135 rows x 3 columns]

### convertion of duration to seconds

In [17]:
tot_eclip['duration'] = (tot_eclip['duration'].str.replace('s' ,' ').str.split('m', expand=True).astype(int).apply(lambda x: x[0] * 60 + x[1], axis=1))
tot_eclip

           date eclipse_type  duration
0    05-18-1901        Total       389
6    09-21-1903        Total       132
8    09-09-1904        Total       380
10   08-30-1905        Total       226
14   01-14-1907        Total       145
..          ...          ...       ...
431  06-02-2095        Total       198
433  05-22-2096        Total       366
435  05-11-2097        Total       190
441  09-14-2099        Total       318
443  09-04-2100        Total       212

[135 rows x 3 columns]

### Date of the longuest total eclipse

In [7]:
tot_eclip.loc[tot_eclip['duration'] == tot_eclip['duration'].max()]

           date eclipse_type  duration
125  06-20-1955        Total       428

In [8]:
print(tot_eclip['date'] [tot_eclip['duration'] == tot_eclip['duration'].max()])

125    06-20-1955
Name: date, dtype: str

### AVERAGE DURATION

In [9]:
avg_seconds = tot_eclip['duration'].mean()

avg_minutes = int(avg_seconds // 60)
avg_secs = int(avg_seconds % 60)

print(f"the average duration is {avg_minutes:02d}m{avg_secs:02d}s")

the average duration is 03m31s

### NEXT 10 ECLIPSE

In [10]:
today = pd.Timestamp.today()
today

Timestamp('2026-08-01 22:20:42.905039')

In [11]:
df['date'] = pd.to_datetime(df['date'])
upcoming = df[df['date'] > today].sort_values('date').head(10)
upcoming

,date,eclipse_type,magnitude,duration,region
277,2026-08-12,Total,1.039,02m18s,"n N. America, w Africa, Europe [Total: Arctic, Greenland, Iceland, Spain]"
278,2027-02-06,Annular,0.928,07m51s,"S. America, Antarctica, w & s Africa [Annular: Chile, Argentina, Atlantic]"
279,2027-08-02,Total,1.079,06m23s,"Africa, Europe, Mid East, w & s Asia [Total:Morocco, Spain, Algeria, Libya, Egypt, Saudi Arabia, Yemen, Somalia]"
280,2028-01-26,Annular,0.921,10m27s,"e N. America, C. & S. America, w Europe, nw Africa [Annular: Ecuador, Peru, Brazil, Suriname, Spain, Portugal]"
281,2028-07-22,Total,1.056,05m10s,"SE Asia, E. Indies, Australia, N.Z. [Total: Australia, N. Z.]"
282,2029-01-14,Partial,0.871,NaN,"N. America, C. America"
283,2029-06-12,Partial,0.458,NaN,"Arctic, Scandanavia, Alaska, n Asia, n Canada"
284,2029-07-11,Partial,0.230,NaN,"s Chile, s Argentina"
285,2029-12-05,Partial,0.891,NaN,"s Argentina, s Chile, Antarctica"
286,2030-06-01,Annular,0.944,05m21s,"Europe, n Africa, Mid East, Asia, Arctic, Alaska [Annular: Algeria, Tunisia, Greece, Turkey, Russia, n. China, Japan]"